const { BASE_URL, API_KEY, BASE_URL_WEATHER, API_KEY_WEATHER, BASE_URL_CURRENCY, API_KEY_CURRENCY } = process.env;

export default {
  BASE_URL: BASE_URL,
  API_KEY: API_KEY,
  BASE_URL_WEATHER: BASE_URL_WEATHER,
  API_KEY_WEATHER: API_KEY_WEATHER,
  BASE_URL_CURRENCY: BASE_URL_CURRENCY,
  API_KEY_CURRENCY: API_KEY_CURRENCY,
};